# -*- coding: utf-8 -*-
"""Jogo da forca.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ukQDq6Ac3xwa6K558OYWsCcE7TpYZWL6
"""

import random


bancodepalavras = ["agua", "terra", "fogo", "anomalia", "dicionario", "pedra", "rio", "menina", "coragem", "remix", "perdedor", "sinais", "gasolina", "supremo", "radar", "software", "hardware", "compilado", "rede", "neural", "pantera", "assombrado", "rapido", "assombraçao"]
forca = random.choice(bancodepalavras).upper()
tentativas = True
erros = 9
faltando = 1

def localizar(texto,palavra):
  posicoes = []
  for i in range(len(texto)):
    if texto[i] == palavra:
      posicoes.append(i)
  return posicoes

palavra = forca
print(f"Dica: A palavra contem {len(forca)} letras\n")

palavrasec = list('_' * len(palavra))
print(palavrasec)
n=0

while tentativas == True:
  letra = input("\nInsira uma letra: \n").upper()
  print(f"\nA letra inserida foi: {letra}\n")
  if letra in palavra:
    posicao = localizar(palavra, letra)
    for i in posicao:
      palavrasec[i]= letra
      print(palavrasec)
      faltando = palavrasec.count('_')
      print(f"Ainda faltam: {faltando} letras.\n")
    if faltando == 0:
      print("\nVocê ganhou!")
      break
  else:
    print ('''Você errou !!!
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=''')
    erros = erros - 1
    if erros == 8:
      print(f"Você ainda tem {erros} tentativas \n(0.0)")
    elif erros == 7:
      print(f'''Você ainda tem {erros} tentativas

      (0.0)
        |
             \n''')
    elif erros == 6:
      print(f'''Você ainda tem {erros} tentativas

      (0.0)
        |
        |  \n''')
    elif erros == 5:
      print(f'''Você ainda tem {erros} tentativas

      (0.0)
       /|
        |  \n''')
    elif erros == 4:
      print(f'''Você ainda tem {erros} tentativas

      (0.0)
       /| \

        |
         \n''')
    elif erros == 3:
      print(f'''Você ainda tem {erros} tentativas

      (0.0)
       /|\
       _|  \n''')
    elif erros == 2:
      print(f'''Você ainda tem {erros} tentativas

      (0.0)
       /|\
       _|_  \n''')
    elif erros == 1:
      print(f'''Você ainda tem {erros} tentativas

      (0.0)
       /|\
       _|_  \n''')
      print("Você perdeu")

    elif erros == 0:
      print(f'''Você ainda tem {erros} tentativas

      (0.0)
       /|\
       _|_  \n''')
      print("Você perdeu")
      tentativas = False