# -*- coding: utf-8 -*-
"""Jogo quente e frio meu.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Rd0vMEmptewjReF_DpqjsqvqcN4xJYGu
"""

!pip install emoji

from random import randint
import emoji

n = randint(0, 50)
c = 0
palpitecomputador = None
i=1
estado = None
saudacao = input("Bem-vindo, insira seu nome ")

while True:

  jogada = int (input (f"{saudacao.capitalize()}, por favor, escolha um número inteiro de 1 a 50 "))
  print(f"Sua jogada foi {jogada}")
  print("-="*15)
  print("-="*15)
  print("-="*15)
  if jogada == n :
    print ("Você ganhou!!!!!")
    print("-="*15)
    break
  elif abs (n -  jogada) == 1:
    print ("🔥🔥🔥🔥🔥🔥Queimando🔥🔥🔥🔥🔥🔥")
    print("-="*15)

  elif abs (n - jogada) == 2 or abs (n- jogada)== 3:
    print("🔥🔥🔥Muito quente🔥🔥🔥!!!")
    print("-="*15)

  elif abs (n - jogada) == 4 or abs (n-jogada)==5 :
    print("🔥🔥Quente🔥🔥")
    print("-="*15)

  elif abs (n - jogada) == 6 or abs (n- jogada) ==7:
    print("🔥Morno🔥")
    print("-="*15)

  elif abs (n - jogada) == 8 or abs (n - jogada == 9):
    print ( "🧊🧊Frio🧊🧊")
    print("-="*15)

  elif abs (n - jogada) == 10:
    print( "🧊🧊🧊Congelando🧊🧊🧊")
    print("-="*15)

  elif abs (n- jogada) >10 :
    print("Você está muito longe")
    print("-="*15)


  if palpitecomputador == None:
    palpitecomputador = randint(0,  50)
    print(f"Palpite computador: {palpitecomputador}")
    print("-="*15)
  elif estado == "Distante":
    palpitecomputador = randint(palpitecomputador-20, palpitecomputador+20)
    print(f"Palpite computador: {palpitecomputador}")
    print("-="*15)
  elif estado == "Congelando":
    palpitecomputador = randint(palpitecomputador-15, palpitecomputador+15)
    print(f"Palpite computador: {palpitecomputador}")
    print("-="*15)
  elif estado == "Frio":
    palpitecomputador = randint(palpitecomputador-10, palpitecomputador+10)
    print(f"Palpite computador: {palpitecomputador}")
    print("-="*15)
  elif estado == "Morno":
    palpitecomputador = randint(palpitecomputador-7, palpitecomputador+7)
    print(f"Palpite computador: {palpitecomputador}")
    print("-="*15)
  elif estado == "Quente":
    palpitecomputador = randint(palpitecomputador-5, palpitecomputador+5)
    print(f"Palpite computador: {palpitecomputador}")
    print("-="*15)
    estado = "Quente"
  elif estado == "Muito Quente":
    palpitecomputador = randint(palpitecomputador-3, palpitecomputador+3)
    print(f"Palpite computador: {palpitecomputador}")
    print("-="*15)
  elif estado == "Queimando":
    palpitecomputador = randint(palpitecomputador-1, palpitecomputador+1)
    print(f"Palpite computador: {palpitecomputador}")
    print("-="*15)
    estado = "Muito Quente"

  if palpitecomputador <= 0 or palpitecomputador >= 51:
    palpitecomputador = randint(0,  51)
    print(f"Palpite computador: {palpitecomputador}")
    print("-="*15)




  if palpitecomputador == n :
    print ("O computador ganhou!!!!!")
    break
  elif abs (n -  palpitecomputador) == 1:
    print ("🔥🔥🔥🔥🔥🔥O computador está Queimando🔥🔥🔥🔥🔥🔥")
    estado = "Queimando"

  elif abs (n - palpitecomputador) == 2 or abs (n- palpitecomputador)== 3:
    print("🔥🔥🔥O computador está Muito quente🔥🔥🔥!!!")
    estado = "Muito Quente"
  elif abs (n - palpitecomputador) == 4 or abs (n-palpitecomputador)==5 :
    print("🔥🔥O computador está Quente🔥🔥")
    estado = "Quente"
  elif abs (n - palpitecomputador) == 6 or abs (n- palpitecomputador) ==7:
    print("🔥O computador está Morno🔥")
    estado = "Morno"

  elif abs (n - palpitecomputador) == 8 or abs (n - palpitecomputador == 9):
    print ( "🧊🧊O computador está Frio🧊🧊")
    estado = "Frio"
  elif abs (n - palpitecomputador) == 10:
    print( "🧊🧊🧊O computador está Congelando🧊🧊🧊")
    estado = "Congelando"
  elif abs (n- palpitecomputador) >10 :
    print("O computador está muito longe")
    estado = "Distante"

print ('fim do jogo')